import type { BlogPost } from './types';

export const BLOG_DATA: BlogPost[] = [
  {
    slug: 'rooftop-celebration-ideas',
    title: '5 Reasons a Rooftop Restaurant is Perfect for Your Next Celebration',
    date: 'July 22, 2024',
    author: 'Posh Lounge Team',
    summary: 'From breathtaking views to an unforgettable ambiance, discover why celebrating your special moments high above the city at Posh Lounge is an experience like no other.',
    imageUrl: 'https://res.cloudinary.com/dy80ftu9k/image/upload/v1755443220/Heo_Secion_image_pzcktp.png',
    content: [
      { type: 'paragraph', text: 'When it comes to celebrating life\'s special moments, the setting is just as important as the occasion itself. A rooftop restaurant offers a unique blend of elegance, excitement, and exclusivity that can elevate any event from memorable to truly unforgettable. Here are five reasons why Posh Lounge Rooftop is the perfect venue for your next celebration.' },
      { type: 'heading', text: '1. The Unbeatable Views' },
      { type: 'paragraph', text: 'Imagine clinking glasses against a backdrop of the glittering Dhaka skyline. A rooftop setting provides a stunning panoramic view that evolves from a golden sunset to a blanket of city lights. This breathtaking scenery creates a magical atmosphere and offers incredible photo opportunities you just can\'t get anywhere else.' },
      { type: 'heading', text: '2. An Atmosphere of Exclusivity' },
      { type: 'paragraph', text: 'Being high above the hustle and bustle of the city streets creates an intimate and exclusive vibe. It feels like a private escape, allowing you and your guests to relax and connect in a sophisticated environment. Whether it\'s a romantic dinner, a birthday bash, or a corporate event, the ambiance of a rooftop lounge adds a touch of class.' },
      { type: 'heading', text: '3. Dining Under the Stars' },
      { type: 'paragraph', text: 'There\'s something inherently romantic and special about dining al fresco. At Posh Lounge, you can enjoy our exquisite menu under the open sky. The combination of fresh air, delicious food, and the vast expanse above creates a multi-sensory dining experience that is both refreshing and luxurious.' },
      { type: 'heading', text: '4. A Versatile and Stylish Venue' },
      { type: 'paragraph', text: 'Our rooftop space is designed to be both stylish and versatile. It can be transformed to suit any occasion, from a chic cocktail party to an elegant sit-down dinner. The modern decor, comfortable seating, and ambient lighting work together to create a sophisticated space that will impress your guests.' },
      { type: 'heading', text: '5. A Complete Sensory Experience' },
      { type: 'paragraph', text: 'At Posh Lounge, we believe a celebration should engage all the senses. It\'s not just about the taste of our gourmet dishes or the sight of the stunning views. It\'s about the curated music that sets the mood, the gentle breeze, and the impeccable service that makes you feel pampered. It all combines to create a holistic experience that lingers long after the night is over.' },
    ],
  },
  {
    slug: 'art-of-fusion-flavors',
    title: 'The Art of Fusion: Exploring the Unique Flavors of Posh Lounge',
    date: 'July 15, 2024',
    author: 'Chef\'s Table',
    summary: 'Dive into the culinary philosophy behind our menu, where Thai inspirations meet global cuisine. Learn about our signature dishes like the Thai Pizza and Chili Crab Crunch.',
    imageUrl: 'https://res.cloudinary.com/dukaroz3u/image/upload/v1755442998/aymqwt3klhrvaqygjcqp.jpg',
    content: [
        { type: 'paragraph', text: 'At the heart of Posh Lounge is a passion for culinary innovation. Our menu is a testament to the art of fusion, a delicate dance between the bold, aromatic flavors of Thailand and the diverse techniques of global cuisine. It’s a journey for the palate, where familiar tastes are reimagined and new classics are born.' },
        { type: 'heading', text: 'What is Fusion Cuisine?' },
        { type: 'paragraph', text: 'Fusion cuisine is about more than just mixing ingredients from different countries. It’s a philosophy that respects tradition while embracing creativity. It involves understanding the core flavor profiles of each culinary style and finding harmonious ways to blend them, creating dishes that are both surprising and delightfully coherent.' },
        { type: 'heading', text: 'Signature Fusions on Our Menu' },
        { type: 'paragraph', text: 'Our chefs have masterfully crafted a menu that showcases this philosophy. Take our bestselling **Thai Pizza**, for example. We\'ve taken the beloved Italian staple and infused it with the quintessential sweet, sour, and spicy notes of Thai cuisine. It\'s an unexpected combination that has quickly become a guest favorite.' },
        { type: 'paragraph', text: 'Another star is the **Chili Crab Crunch**. This dish reimagines the famous Singaporean chili crab by transforming it into a crispy, bite-sized delight. We capture the essence of the rich, savory sauce and succulent crab meat in a form that’s perfect for sharing and socializing.' },
        { type: 'heading', text: 'Commitment to Freshness' },
        { type: 'paragraph', text: 'True fusion is only possible with the highest quality ingredients. We are committed to sourcing the freshest local produce, premium meats, and authentic spices. This dedication ensures that every dish we serve is vibrant, flavorful, and a true representation of our culinary vision. From our kitchen to your table, we invite you to explore a world of flavor, right here above the Dhaka skyline.' },
    ],
  },
  {
    slug: 'evening-above-dhaka',
    title: 'An Evening Above Dhaka: More Than Just a Meal, It\'s an Experience',
    date: 'July 8, 2024',
    author: 'Posh Lounge Team',
    summary: 'We believe dining is an experience for all senses. Discover how we combine stunning cityscapes, curated music, and exceptional service to create unforgettable evenings.',
    imageUrl: 'https://res.cloudinary.com/dukaroz3u/image/upload/v1755442997/panr3hkcccjv6ljojlmb.jpg',
    content: [
      { type: 'paragraph', text: 'An evening at Posh Lounge Rooftop transcends the traditional dining experience. We’ve meticulously crafted an environment where every element—from the ambiance to the service—comes together to create a symphony for the senses. It’s not just about what’s on your plate; it’s about the memories you create while you’re with us.' },
      { type: 'heading', text: 'The Golden Hour Transformation' },
      { type: 'paragraph', text: 'The experience begins as the sun starts its descent, casting a warm, golden glow over the city. This is the golden hour, a magical time when the skyline is painted with hues of orange, pink, and purple. It’s the perfect moment for a handcrafted cocktail, as you watch the city transition from the energy of the day to the sparkle of the night.' },
      { type: 'heading', text: 'A Soundtrack for the Senses' },
      { type: 'paragraph', text: 'As darkness falls, the atmosphere is enhanced by our carefully curated soundtrack. Our music selection is designed to complement the sophisticated yet relaxed vibe of the lounge. It’s present enough to add energy but subtle enough to allow for intimate conversations, creating the perfect auditory backdrop for your evening.' },
      { type: 'heading', text: 'Service That Anticipates' },
      { type: 'paragraph', text: 'Exceptional service is the cornerstone of the Posh Lounge experience. Our team is trained to be attentive but not intrusive, ensuring your needs are met before you even have to ask. From recommending the perfect wine pairing to ensuring your comfort, we pride ourselves on providing a seamless and personalized service experience.' },
      { type: 'paragraph', text: 'At Posh Lounge, every detail is considered to ensure your evening is nothing short of spectacular. We invite you to join us and discover an experience that is far more than just a meal.' },
    ],
  },
];