
import type { MenuCategory } from './types';

export const MENU_DATA: MenuCategory[] = [
  {
    category: 'Appetizers',
    items: [
      { name: 'Chicken Nan Bun', price: '399 BDT', quantity: '5 Pcs' },
      { name: 'Fried Calamari Rings', price: '359 BDT' },
      { name: 'Prawn Tempura', price: '399 BDT', quantity: '4 Pcs / More' },
      { name: 'Fish & Chips', price: '399 BDT' },
      { name: 'Fried Cheese Wonton', price: '299 / 430 BDT', quantity: '4 Pcs / 6 Pcs / or More' },
      { name: 'Bangkok Fried Chicken', price: '399 BDT', quantity: '4 Pcs / More' },
      { name: 'Wings', price: '299 BDT', quantity: '6 Pcs' },
      { name: 'Roasted Wadges', price: '219 BDT' },
      { name: 'Korean Chicken, Mild Spice', price: '289 BDT' },
    ],
  },
  {
    category: 'Dumplings',
    items: [
      { name: 'Chicken & Prawn Sui Mai', price: '299 / 439 BDT', quantity: '4 Pcs / 6 Pcs' },
      { name: 'Chicken & Lemongrass Sui Mai', price: '289 / 419 BDT', quantity: '4 Pcs / 6 Pcs' },
      { name: 'Nori-Wrapped Sui Mai', price: '319 / 459 BDT', quantity: '4 Pcs / 6 Pcs' },
      { name: 'Broccoli With Cheddar Cheese', price: '319 / 459 BDT', quantity: '4 Pcs / 6 Pcs' },
      { name: 'Beef & Mushroom Dumpling', price: '319 / 459 BDT', quantity: '4 Pcs / 6 Pcs' },
      { name: 'Crystal Cheese Truffle', price: '319 / 459 BDT', quantity: '4 Pcs / 6 Pcs' },
      { name: 'Wonton In Chili Oil', price: '299 / 439 BDT', quantity: '4 Pcs / 6 Pcs' },
      { name: 'Chicken Cheung Fun', price: '319 / 459 BDT', quantity: '4 Pcs / 6 Pcs' },
      { name: 'Beef & Basil Potsticker', price: '319 / 459 BDT', quantity: '4 Pcs / 6 Pcs' },
      { name: 'Crab and Cream Cheese Rangoon', price: '319 / 459 BDT', quantity: '4 Pcs / 6 Pcs' },
      { name: 'Prawn & Cream Cheese Rangoon', price: '319 / 459 BDT', quantity: '4 Pcs / 6 Pcs' },
      { name: 'Edamammy Prawn Hargao', price: '319 / 459 BDT', quantity: '4 Pcs / 6 Pcs' },
      { name: 'Prwan Hargao', price: '319 / 459 BDT', quantity: '4 Pcs / 6 Pcs' },
    ],
  },
  {
    category: 'Sushi',
    items: [
      { name: 'Caviar And Tuna Cut', price: '299 / 436 BDT', quantity: '4 Pcs / 6 Pcs', description: 'Fresh, Thin-Cut Tuna Paired With Rich, Briny Caviar' },
      { name: 'Cheese Crab Crunch', price: '299 / 436 BDT', quantity: '4 Pcs / 6 Pcs', description: 'Crispy On The Outside, Creamy On The Inside - This Savory Delight Features Succulent Crab Stick' },
      { name: 'Chili Crab Crunch', price: '299 / 436 BDT', quantity: '4 Pcs / 6 Pcs', description: 'Crispy Golden Bites Filled With Succulent Crab Meat, Tossed In Our Signature Sweet And Spicy Chili Sauce' },
      { name: 'Yaki (Grilled) Tempura Roll', price: '299 / 436 BDT', quantity: '4 Pcs / 6 Pcs', description: 'A Savory Fusion Roll Featuring Crispy Tempura Shrimp, Creamy Cheese And Cucumber Wrapped In Seasoned Sushi Rice And Nori' },
      { name: 'Volano Maki Roll', price: '299 / 436 BDT', quantity: '4 Pcs / 6 Pcs', description: 'A Fiery Fusion Of Smoky Finish, Flavor Topped With Baked Crab Mix, Drizzled With Spicy Mayo' },
      { name: 'Tuna Maki Sushi', price: '299 / 436 BDT', quantity: '4 Pcs / 6 Pcs', description: 'Delicate Rolls Of Seasoned Sushi Rice And Fresh, Sashimi-Grade Tuna Wrapped In Crisp Seaweed' },
    ],
  },
  {
    category: 'Soup',
    items: [
      { name: 'Thai Thick Soup', price: 'Regular 250 / Large 490 BDT', description: 'Chicken, Mushrooms, Thai Herbs, Lemongrass, Lime Juice, Cornstarch' },
      { name: 'Tom Yum Soup', price: 'Regular 260 / Large 499 BDT', description: 'A Spicy And Sour Thai Soup With Lemongrass, Lime Leaves, Chili, Lime Juice, Fish Sauce, And Fresh Prawns Or Chicken' },
      { name: 'Beef Noodle Soup', price: 'Regular 299 / Large 560 BDT', description: 'Beef, Vegetable And Noodles in Broth' },
      { name: 'Cream Of Mushroom Soup', price: 'Regular 260 / Large 480 BDT', description: 'Fresh Mushrooms, Cream, Butter, Garlic, Onion, Herbs, Vegetable Stock' },
      { name: 'Special Seafood Soup', price: 'Regular 279 / Large 529 BDT', description: 'Prawn, Squid, Octopus And Mushroom In Clear Soup' },
    ],
  },
  {
    category: 'Rice',
    items: [
      { name: 'Posh Lounge Special Seafood Fried Rice', price: '339 BDT', description: 'Fragrant Jasmine Rice Stir-Fried With Succulent Prawns, Tender Calamari, And Fresh Fish, Tossed In Our Signature Seafood Sauce With Garlic, Chili, And Seasonal Vegetables' },
      { name: 'Tom Yum Mixed Fried Rice', price: '319 BDT', description: 'A Bold Fusion Of Prawns, Chicken, And Squid Stir-Fried With Jasmine Rice, Lemongrass, Chili, And Tom Yum Spices-Finished With Fresh Herbs And A Splash Of Lime' },
      { name: 'Egg Fried Rice', price: '199 BDT', description: 'Tossed Jasmine Rice With Fluffy Scrambled Eggs, Garlic, Spring Onions, And Light Soy Sauce-Simple, Savory, And Satisfying' },
      { name: 'Special Mix Fried Rice', price: '349 BDT', description: 'A Hearty Blend Of Chicken, Prawns, Beef, And Seasonal Vegetables Stir-Fried With Fragrant Jasmine Rice, Savory Soy Sauce, And Aromatic Spices-Served With A Touch Of Sesame Oil' },
      { name: 'PL Special Naga Fried Rice', price: '329 BDT', description: 'Tossed Rice With Tender Chicken, Spicy Naga Chili, Mixed Vegetables, And House Special Spices' },
    ],
  },
  {
    category: 'Noodles & Ramen',
    items: [
      { name: 'Pad Thai Noodles', price: '399 BDT', description: "Thailand's Iconic Noodle Dish With A Perfect Balance Of Tangy, Sweet, And Spicy" },
      { name: 'Fried Spicy Mix Noodles', price: '399 BDT', description: 'Loaded With Veggies, Chicken, Prawn, Spice & Flavor' },
      { name: 'Chili Oil Mix Noodles', price: '399 BDT', description: 'Bold, Fragrant Noodles Tossed In Our Signature House-Made Chili Oil With Garlic, Soy, And A Hint Of Tang' },
      { name: 'House Special Mix Noodles', price: '399 BDT', description: 'A Sizzling Medley Of Stir-Fried Noodles Tossed With Juicy Chicken, Tender Beef, Fresh Veggies, And A Secret House Sauce — Bold, Savory, And Full Of Flavor' },
      { name: 'Korean Chicken Ramen', price: '429 BDT' },
      { name: 'Spicy Korea Beef Ramen', price: '499 BDT' },
      { name: 'Tomyum Seafood Ramen', price: '489 BDT' },
    ],
  },
  {
    category: 'Salad',
    items: [
      { name: 'Thai Seafood Salad', price: '349 BDT', description: 'Fresh Prawns, Squid, And Mussels Tossed With Crisp Vegetables, Fragrant Herbs' },
      { name: 'Thai Special Papaya Salad', price: '349 BDT', description: 'A Vibrant Mix Of Shredded Green Papaya, Fresh Chilies, Garlic, Lime Juice, Tomatoes, And Peanuts' },
      { name: 'Thai Chicken Cashew-Nut Salad', price: '349 BDT', description: 'Tender Grilled Chicken Tossed With Crunchy Roasted Cashews, Fresh Greens, Bell Peppers, And A Zesty Thai Dressing' },
      { name: 'Thai Beef Salad', price: '349 BDT', description: 'Tender Slices Of Grilled Beef Tossed With Fresh Herbs, Crisp Vegetables, And A Zesty Lime-Chili Dressing' },
      { name: 'Posh Special Green Chicken Salad', price: '339 BDT', description: 'Tender Grilled Chicken Breast Served On A Bed Of Fresh Greens, Crisp Cucumbers, Creamy Avocado, And Herb Vinaigrette' },
    ],
  },
  {
    category: 'Chicken',
    items: [
      { name: 'Thai Orange Chicken', price: '389 BDT', description: 'Crispy Golden Chicken Tossed In A Sweet And Tangy Thai Orange Glaze' },
      { name: 'Soy Glazed Ginger Chicken', price: '389 BDT', description: 'Tender Chicken Thighs Glazed In A Rich Soy-Ginger Sauce' },
      { name: 'Thai Chicken With Basil Leaf', price: '389 BDT', description: 'Stir-Fried Tender Chicken With Fragrant Thai Basil, Garlic, And Chili In A Savory-Spicy Sauce' },
      { name: 'Sichuan Cashews Chicken', price: '399 BDT', description: 'Tender Chicken Stir-Fried With Crunchy Cashews, Spicy, Tangy Sichuan Sauce' },
      { name: 'Sriracha Chicken With Mushroom', price: '379 BDT', description: 'Tender Chicken And Sautéed Mushroom To Perfection, Tossed In A Bold And Spicy Sriracha Sauce' },
      { name: 'Chicken Sizzling', price: '399 BDT', description: 'Tender Chicken Pieces Cooked To Perfection With Fresh Vegetables And A Savory Sauce, Served Piping Hot On A Sizzling Platter For A Burst Of Flavor And Aroma' },
      { name: 'PL Special Thai Red Curry', price: '419 BDT', description: 'A Rich And Creamy Blend Of Aromatic Thai Spices, Coconut Milk, And Fresh Herbs' },
      { name: 'PL Special Thai Green Curry', price: '419 BDT', description: 'A Vibrant And Aromatic Blend Of Fresh Green Chilies, Fragrant Herbs, And Creamy Coconut Milk Simmered With Tender Chicken And Crisp Vegetables' },
    ],
  },
  {
    category: 'Beef',
    items: [
      { name: 'Beef Bulgogi', price: '549 BDT', description: 'Tender, Marinated Slices Of Beef Grilled To Perfection With A Savory Blend Of Soy, Garlic, And Sesame' },
      { name: 'Beef Mahalak', price: '539 BDT', description: 'A Rich And Flavorful Beef Curry Simmered To Perfection With Aromatic Spices, Tender Chunks Of Beef' },
      { name: 'Beef Sizzling', price: '559 BDT', description: 'Tender Strips Of Marinated Beef, Stir-Fried With Bell Peppers, Onions, And A Savory Sauce, Served On A Hot Sizzling Plate' },
      { name: 'Roasted Beef', price: '549 BDT', description: 'Tender Slices Of Slow-Roasted Beef, Seasoned With Herbs And Spices' },
      { name: 'Thai Beef In Red Curry', price: '559 BDT', description: 'Tender Beef Simmered In A Rich, Aromatic Thai Red Curry Sauce With Coconut Milk, Fresh Herbs, And A Hint Of Spice' },
      { name: 'Thai Beef In Green Curry', price: '559 BDT', description: 'Tender Beef Simmered In A Rich, Aromatic Thai Green Curry With Coconut Milk, Fresh Herbs, And Seasonal Vegetables' },
    ],
  },
  {
    category: 'Seafood',
    items: [
      { name: 'Stir-Fried Calamari', price: '449 BDT', description: 'Calamari In Spicy Red Pepper Sauce' },
      { name: 'Oriental Chili Fish', price: '459 BDT', description: 'Slices Of Red Fish And Capsicum Cooked in Chili Oil And Soy Sauce' },
      { name: 'Hunan Prawn', price: '489 BDT', description: 'Stir-Fried Chunky Prawn In A Blend Of Chili, Garlic And Soy Sauce' },
      { name: 'Naga Prawn', price: '499 BDT', description: 'Prawn stir-fried in Garlic and House Special Chili' },
      { name: 'Fisherman\'s Basket', price: '499 BDT', description: 'Sliced Fish, Squid And Shrimp In A Mixture Of Basil, Oriental Sauces And Bell Peppers' },
      { name: 'PL Special Chili Crab', price: '499 BDT', description: 'Crab With Spicy, Savory Sauce' },
      { name: 'Spicy Prawn Sizzling', price: '519 BDT', description: 'Juicy Prawns Marinated In A Fiery Blend Of Spices, Stir-Fried With Fresh Vegetables, And Served Sizzling Hot On A Cast Iron Plate' },
    ],
  },
  {
    category: 'Platters & Set Menus',
    items: [
        { name: 'Classic Set Meal (Chicken)', price: '450 BDT', description: 'Thai Fried Rice, Bangkok Style Fried Chicken (1pc), Chicken Curry, Thai Style Vegetable' },
        { name: 'Classic Set Meal (Fish)', price: '500 BDT', description: 'Prawn Tempura, Hot Chilli Fish Curry, Thai Special Fried Rice, Thai Mixed Vegetables' },
        { name: 'Classic Set Meal (Beef)', price: '500 BDT', description: 'Thai Special Fried Rice, Bangkok Style Fried Chicken (1pc), Beef Curry, Thai Style Vegetable' },
        { name: 'Premium Platter (BBQ Chicken)', price: '590 BDT', description: 'Sizzling Platter: BBQ Chicken Steak, Sauteed Vegetable, Chef Special Sauce, Roasted Tomatoes, choice of Thai Fried Rice or Mashed potatoes' },
        { name: 'Premium Platter (Mongolian Chicken)', price: '590 BDT', description: 'Sizzling Platter: Mongolian Chicken Steak, Sauteed Vegetable, Chef Special Sauce, Roasted Tomatoes, choice of Thai Fried Rice or Mashed potatoes' },
        { name: 'Premium Platter (Peri Peri Chicken)', price: '590 BDT', description: 'Sizzling Platter: Peri Peri Chicken Steak, Sauteed Vegetable, Wadges, choice of Thai Fried Rice or Mashed potatoes' },
        { name: 'PL Special Bento Box', price: '690 BDT' },
        { name: 'Signature Bento Box', price: '690 BDT' },
        { name: 'Couple Platter (Candle Night Dinner)', price: '1699 BDT', description: 'For 2: Tom Yum Seafood Soup, Cheese Wonton, Fish And Chips, Thai Fried Rice, Chicken Nan Bun, Fish And Prawn Chilli Paste, Thai Mixed Vegetables, Cafe Latte, Water' },
        { name: 'Family Platter (4 Person)', price: '4999 BDT', description: 'For 4: Tom Yum Seafood Soup, Potato Wedges, Cheese Wonton, Mixed Fried Rice, Thai Mixed Vegetables, Chicken With Red Curry, Bangkok Fried Chicken, Fried Whole Snapper With Chilli Sauce, Soft Drinks, Brownie, Special Coffee' },
    ],
  },
  {
    category: 'Rice Bowls',
    items: [
        { name: 'Sea Food Rice Bowl', price: '499 BDT' },
        { name: 'PL Special Rice Bowl', price: '475 BDT' },
        { name: 'Chilli Chicken Rice Bowl', price: '455 BDT' },
        { name: 'Naga Rice Bowl', price: '460 BDT' },
        { name: 'Tomyum Rice Bowl', price: '480 BDT' },
        { name: 'Student Meal', price: '350 BDT' },
    ],
  },
  {
    category: 'Pizza',
    items: [
        { name: 'Margarita Pizza (The Classic)', price: 'M: 550 / L: 650 / F: 950' },
        { name: 'The 4 Cheese (With crispy beef bacon bits)', price: 'M: 650 / L: 750 / F: 1095' },
        { name: 'Spicy BBQ (Naga chicken with bacon)', price: 'M: 650 / L: 750 / F: 1095' },
        { name: 'The Kala Bhuna Pizza (Authentic beef)', price: 'M: 850 / L: 950 / F: 1295' },
        { name: 'The Pepperonia (Classic pepperoni)', price: 'M: 695 / L: 795 / F: 1195' },
        { name: 'Mushroom Lovers Pizza (Loaded)', price: 'M: 650 / L: 750 / F: 1095' },
        { name: 'Chicken Alfredo Pizza (Creamy)', price: 'M: 650 / L: 750 / F: 1095' },
        { name: 'Shrimp Lovers Pizza (Spicy)', price: 'M: 850 / L: 995 / F: 1195' },
        { name: 'Pomo Rosso Special Pizza', price: 'M: 850 / L: 995 / F: 1195' },
        { name: 'Spicy Corned Beef', price: 'M: 749 / L: 849 / F: 1149' },
        { name: 'Beef Bolognese', price: 'M: 749 / L: 849 / F: 1149' },
        { name: 'Thai Pizza', price: 'M: 799 / L: 999 / F: 1199' },
        { name: 'Meat Lovers', price: 'M: 799 / L: 999 / F: 1199' },
    ],
  },
  {
    category: 'Fast Food',
    items: [
        { name: 'Creamy Chicken Fosulia Pasta', price: '450 BDT' },
        { name: 'Creamy Shrimp Pasta', price: '450 BDT' },
        { name: 'Cheese Cream Pasta', price: 'Chicken 450 / Beef 550 BDT' },
        { name: 'Spicy Cheese Cream Pasta', price: 'Chicken 450 / Beef 550 BDT' },
        { name: 'Pasta Alfredo', price: 'Chicken 450 / Beef 550 BDT' },
        { name: 'Posh Lounge Special Pasta', price: 'Chicken 450 / Beef 550 BDT' },
        { name: 'Pasta Fusion', price: 'Chicken 450 / Beef 550 BDT' },
        { name: 'Spicy BBQ Chicken Sandwich', price: '345 BDT' },
        { name: 'Posh Lounge Special Cheese Sandwich', price: '345 BDT' },
        { name: 'Chicken Club Sandwich', price: '390 BDT' },
        { name: 'Italian Sandwich', price: '360 BDT' },
        { name: 'Posh Lounges Jumbo Burger', price: 'Chicken 345 / Beef 460 BDT' },
        { name: 'Spicy Juicy Burger', price: 'Chicken 345 / Beef 460 BDT' },
    ],
  },
  {
    category: 'Coffee & Drinks',
    items: [
        { name: 'Espresso (Single)', price: '170 BDT' },
        { name: 'Espresso (Double)', price: '190 BDT' },
        { name: 'Macchiato', price: '180 BDT' },
        { name: 'Americano', price: '190 BDT' },
        { name: 'Cappuccino', price: '240 BDT' },
        { name: 'Cafe Latte', price: '240 BDT' },
        { name: 'Flavoured Latte', price: '290 BDT', description: 'Vanilla, Hazelnut, Caramel, Butterscotch' },
        { name: 'Posh Lounge Mocha', price: '350 BDT' },
        { name: 'White Mocha', price: '330 BDT' },
        { name: 'Dark Mocha', price: '300 BDT' },
        { name: 'Hot Chocolate', price: '260 BDT' },
        { name: 'Iced Posh Lounge Mocha', price: '290 BDT' },
        { name: 'Iced White Mocha', price: '280 BDT' },
        { name: 'Iced Dark Mocha', price: '260 BDT' },
        { name: 'Iced Cafe Latte', price: '230 BDT' },
        { name: 'Iced Americano', price: '220 BDT' },
        { name: 'Iced Flavoured Latte', price: '250 BDT', description: 'Vanilla, Hazelnut, Caramel, Butterscotch' },
        { name: 'White Mocha (Blended)', price: '360 BDT' },
        { name: 'Dark Mocha (Blended)', price: '350 BDT' },
        { name: 'Posh Lounge Mocha (Blended)', price: '380 BDT' },
        { name: 'Hot Chocolate Frappe', price: '300 BDT' },
        { name: 'Snickers Mocha', price: '400 BDT' },
        { name: 'Frozen Brownie', price: '450 BDT' },
        { name: 'Orange Juice', price: '220 BDT' },
        { name: 'Pineapple Juice', price: '220 BDT' },
        { name: 'Milk Chocolicious', price: '250 BDT' },
        { name: 'Vanilla Frost', price: '250 BDT' },
        { name: 'Oreo Bliss', price: '250 BDT' },
        { name: 'Kitkat Shake', price: '250 BDT' },
        { name: 'Strawberry Splash', price: '250 BDT' },
        { name: 'Limoncello Spritz', price: '200 BDT' },
        { name: 'Mango Mint Mojito', price: '290 BDT' },
    ],
  },
  {
    category: 'Dessert & Tea',
    items: [
        { name: 'Golden Drops In Coconut Snow', price: '246 BDT' },
        { name: 'Coconut Sunset Delight', price: '286 BDT' },
        { name: 'Honey Silk With Nut Crystals', price: '236 BDT' },
        { name: 'Chocolate Brownie', price: '150 BDT' },
        { name: 'Chocolate Nut Brownie With Ice Cream', price: '200 BDT' },
        { name: 'Vanilla/Chocolate/Strawberry Ice Cream', price: '150 BDT' },
        { name: 'Chocolate Mousse', price: '175 BDT' },
        { name: 'Oreo mousse', price: '175 BDT' },
        { name: 'Straw Perl (Strawberry)', price: '349 BDT' },
        { name: 'Perl Blue (Blueberry)', price: '349 BDT' },
        { name: 'Green Perl (Apple)', price: '349 BDT' },
        { name: 'Mellow Perl (Mango)', price: '349 BDT' },
    ],
  },
];